//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: System.Reflection.AssemblyCompanyAttribute("AzureServiceBusExplorerCore")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("AzureServiceBusExplorerCore")]
[assembly: System.Reflection.AssemblyTitleAttribute("AzureServiceBusExplorerCore")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: InternalsVisibleTo("AzureServiceBusExplorerTests")]


// Generated by the MSBuild WriteCodeFragment class.

